# Generated by Django 3.2.18 on 2023-04-02 14:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image2',
            field=cloudinary.models.CloudinaryField(default='blog_image', max_length=255, verbose_name='image2'),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image3',
            field=cloudinary.models.CloudinaryField(default='blog_image', max_length=255, verbose_name='images'),
        ),
    ]
